apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "net.usikkert.kouchat.android"
    compileSdk 36

    defaultConfig {
        applicationId "net.usikkert.kouchat.android"
        minSdk 21
        targetSdk 36
        versionCode 17
        versionName "1.5.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.larswerkman:HoloColorPicker:1.5'
    implementation 'org.jetbrains:annotations:16.0.2'
    implementation 'org.apache.commons:commons-collections4:4.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.19.0'
    testImplementation 'joda-time:joda-time:2.10'

    androidTestImplementation 'com.jayway.android.robotium:robotium-solo:5.6.3'
    androidTestImplementation 'org.easytesting:fest-reflect:1.4.1'
    androidTestImplementation 'com.google.guava:guava:25.1-android'
    androidTestImplementation 'commons-io:commons-io:2.6'
}
